Rewrote the ubuntu init script to be more clean and use correct ubuntu methods

diff --git a/modules/gitorious/templates/etc/init.d/gitorious-unicorn-ubuntu.erb b/modules/gitorious/templates/etc/init.d/gitorious-unicorn-ubuntu.erb
--- a/modules/gitorious/templates/etc/init.d/gitorious-unicorn-ubuntu.erb
+++ b/modules/gitorious/templates/etc/init.d/gitorious-unicorn-ubuntu.erb
@@ -1,50 +1,126 @@
 #! /bin/sh
- 
-# File: /etc/init.d/unicorn
- 
 ### BEGIN INIT INFO
 # Provides:          unicorn
 # Required-Start:    $local_fs $remote_fs $network $syslog
 # Required-Stop:     $local_fs $remote_fs $network $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: starts the unicorn web server
-# Description:       starts unicorn
+# Short-Description: Starts the unicorn web server
+# Description:       Starts the Unicorn webserver bundled with Gitorious
 ### END INIT INFO
+
+# Author: Jarl Stefansson <jarl.stefansson@gmail.com>
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DESC="Unicorn web server for Gitorious"
+NAME=gitorious-unicorn
 DAEMON=<%=app_root%>/bin/unicorn
-DAEMON_OPTS="-c config/unicorn.rb -D"
-NAME=unicorn
-DESC="Unicorn app for gitorious"
-PID=<%=app_root%>/tmp/pids/unicorn.pid 
-bumble="`echo "SNARF" 2>&1 >/dev/null & echo $!`" 
+DAEMON_ARGS="-c config/unicorn.rb -D"
+PIDFILE=<%=app_root%>/tmp/pids/unicorn.pid 
+SCRIPTNAME=/etc/init.d/$NAME
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
+}
+
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
-	$DAEMON $DAEMON_OPTS 2>&1 >/dev/null & echo $! > $PID
-	echo "$NAME."
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   stop)
-	echo -n "Stopping $DESC: "
-        kill -QUIT `cat $PID`
-	echo "$NAME."
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  reload|force-reload)
+	log_daemon_msg "Reloading $DESC" "$NAME"
+	do_reload
+	log_end_msg $?
 	;;
   restart)
-	echo -n "Restarting $DESC: "
-        kill -QUIT `cat $PID`
-	sleep 1
-	$DAEMON $DAEMON_OPTS 2>&1 >/dev/null & echo $! > $PID
-	echo "$NAME."
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
-  reload)
-        echo -n "Reloading $DESC configuration: "
-        kill -HUP `cat $PID`
-        echo "$NAME."
-        ;;
   *)
-	echo "Usage: $NAME {start|stop|restart|reload}" >&2
-	exit 1
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
 	;;
 esac
- 
-exit 0
